### ISSUE TITLE
378 days of rainfall data in 1996?

### ISSUE THREAD

**Issue by kcaylor** [ecohydro/RidgeToReef#5]
In the mpala_ranch_house_rainfall data, 1996 appears to be a really long year. 

year | count | mean | std | min | 25% | 50% | 75% | max
---- | ---- | ---- | --- | --- | --- | --- | --- | ---
1996 | 378.0 | 0.487169 | 3.972918 | 0.0 | 0.0 | 0.0 | 0.0 | 50.800

**Comment by kcaylor** [comment]
Hi @Ntkrell - I see you found the CETRAD data set. 👍 

I think I will still build the Chapter 1 stuff using the Mpala data, and then we can use the larger dataset in Chapter 2 for the parameter estimation/simulation work (which I will start on tomorrow).

**Comment by Ntkrell** [comment]
Yup, that is an issue.
