### ISSUE TITLE
What is up with this ranch house data?

### ISSUE THREAD

**Issue by kcaylor** [ecohydro/RidgeToReef#6]
Okay, one more _strangeness_. Maybe it rained over 768 mm in April, 1989. But probably not...

Year |  Month | Amount
----|-----|------
1989 |  4.0 |     768.35
Name: Rainfall (mm), dtype: float64

One of these months is not like the others:
![image](https://user-images.githubusercontent.com/3585920/44371221-bb56ab80-a492-11e8-9f18-4c1025ed7321.png)

**Comment by kcaylor** [comment]
Sorry about all of these issues... Not sure why this data has so many janky bits.

**Comment by Ntkrell** [comment]
It's L0 data. Never used this -- just providing what I have. So not surprised that some cleaning is required.
